import { FormField } from '@/components/common';
import { BANK_STRINGS, BANK_DROPDOWN_OPTIONS } from '@/constants/bankConstants';

export const bankSearchFields: FormField[] = [
  {
    label: BANK_STRINGS.FORM.BANK_NAME,
    hide: false,
    input: {
      name: 'bankName',
      type: 'text',
      placeholder: 'Enter bank name',
      mandatory: false,
    },
  },
  {
    label: BANK_STRINGS.FORM.BANK_CODE,
    hide: false,
    input: {
      name: 'bankCode',
      type: 'text',
      placeholder: 'Enter bank code',
      mandatory: false,
    },
  },
  {
    label: BANK_STRINGS.FORM.EMAIL_ADDRESS,
    hide: false,
    input: {
      name: 'emailAddress',
      type: 'email',
      placeholder: 'Enter email address',
      mandatory: false,
    },
  },
  {
    label: BANK_STRINGS.FORM.STATUS,
    hide: false,
    dropdown: {
      name: 'status',
      options: BANK_DROPDOWN_OPTIONS.STATUS,
      placeholder: '--Select--',
      mandatory: false,
    },
  },
  {
    label: BANK_STRINGS.FORM.RECORDS_PER_PAGE,
    hide: false,
    dropdown: {
      name: 'recordsPerPage',
      options: BANK_DROPDOWN_OPTIONS.RECORDS_PER_PAGE,
      placeholder: '10',
      mandatory: false,
    },
  },
];

// Mock data for bank search results
export const bankMockData = [
  {
    id: 1,
    bankName: 'First National Bank',
    bankCode: 'FNB001',
    emailAddress: 'contact@firstnational.com',
    status: 'active',
    settlementRoutingNumber: '021000021',
    settlementAccountNumber: '1234567890',
    address1: '123 Main Street',
    city: 'New York',
    state: 'NY',
    zipCode: '10001',
    country: 'USA',
    primaryContactName: 'John Smith',
    contactPhoneNumber: '+1-555-0123',
    localCurrency: 'USD',
  },
  {
    id: 2,
    bankName: 'Global Commerce Bank',
    bankCode: 'GCB002',
    emailAddress: 'info@globalcommerce.com',
    status: 'active',
    settlementRoutingNumber: '021000022',
    settlementAccountNumber: '2345678901',
    address1: '456 Business Ave',
    city: 'Los Angeles',
    state: 'CA',
    zipCode: '90210',
    country: 'USA',
    primaryContactName: 'Sarah Johnson',
    contactPhoneNumber: '+1-555-0456',
    localCurrency: 'USD',
  },
  {
    id: 3,
    bankName: 'Metropolitan Trust Bank',
    bankCode: 'MTB003',
    emailAddress: 'support@metrotrust.com',
    status: 'inactive',
    settlementRoutingNumber: '021000023',
    settlementAccountNumber: '3456789012',
    address1: '789 Financial Blvd',
    city: 'Chicago',
    state: 'IL',
    zipCode: '60601',
    country: 'USA',
    primaryContactName: 'Michael Davis',
    contactPhoneNumber: '+1-555-0789',
    localCurrency: 'USD',
  },
  {
    id: 4,
    bankName: 'Sunrise Community Bank',
    bankCode: 'SCB004',
    emailAddress: 'hello@sunrisebank.com',
    status: 'pending',
    settlementRoutingNumber: '021000024',
    settlementAccountNumber: '4567890123',
    address1: '321 Community Dr',
    city: 'Miami',
    state: 'FL',
    zipCode: '33101',
    country: 'USA',
    primaryContactName: 'Emily Wilson',
    contactPhoneNumber: '+1-555-0321',
    localCurrency: 'USD',
  },
  {
    id: 5,
    bankName: 'Pacific Coast Bank',
    bankCode: 'PCB005',
    emailAddress: 'contact@pacificcoast.com',
    status: 'suspended',
    settlementRoutingNumber: '021000025',
    settlementAccountNumber: '5678901234',
    address1: '654 Ocean View St',
    city: 'San Francisco',
    state: 'CA',
    zipCode: '94102',
    country: 'USA',
    primaryContactName: 'Robert Brown',
    contactPhoneNumber: '+1-555-0654',
    localCurrency: 'USD',
  },
];